site_name: Clayton UX

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - content.tabs.link
    - content.code.copy
  icon:
    previous: fontawesome/solid/arrow-left
    next: fontawesome/solid/arrow-right

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

docs_dir: revised

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Class 1 - Overview: class1-revised.md
  - Class 2 - UX Methodology: class2-revised.md
  - Class 3 - User-Centered Design: class3-revised.md
  - Class 4 - Problem Statements: class4-revised.md
  - Class 5 - User Flow: class5-revised.md
  - Class 6 - User Testing: class6-revised.md
  - Class 7 - Usability Heuristics: class7-revised.md
  - Class 8 - Low-Fidelity Wireframes: class8-revised.md
  - Class 9 - High-Fidelity Wireframes: class9-revised.md
  - Final Overview: ClassF-Revised.md