site_name: Clayton UX

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.tabs.link
    - content.code.copy
  icon:
    previous: fontawesome/solid/arrow-left
    next: fontawesome/solid/arrow-right

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

docs_dir: revised

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Class 1: class1-revised.md
  - Class 2: class2-revised.md
  - Class 3: class3-revised.md
  - Class 4: class4-revised.md
  - Class 5: class5-revised.md
  - Class 6: class6-revised.md
  - Class 7: class7-revised.md
  - Class 8: class8-revised.md
  - Class 9: class9-revised.md
  - Final: ClassF-Revised.md